import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import profile from "../public/profile.png";
import design from "../public/design.png";
import code from "../public/code.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [selectedProject, setSelectedProject] = useState(null);

  const projects = [
    {
      title: "Scout Search Engine",
      image: web2,
      github: "https://github.com/gauravsewani/search",
      demo: "https://scout1.vercel.app/",
      description:
        "A search engine clone built to mimic the functionality of popular search engines.",
      detailedDescription:
        "Scout Search Engine is a clone that aims to replicate the essential features of popular search engines. It provides users with the ability to perform web searches and receive relevant results.",
      technologies: ["React", "Emotion", "MUI"],
    },
    {
      title: "GoPlayer Game Search",
      image: web3,
      github: "https://github.com/gauravsewani/goplayer-app",
      demo: "https://goplayer.vercel.app/",
      description:
        "A game search and details website utilizing the rawg.io API for game information.",
      detailedDescription:
        "GoPlayer Game Search is a web application that allows users to search for games and view detailed information about them, utilizing the rawg.io API to fetch game data.",
      technologies: ["React", "Redux", "Axios", "Framer Motion"],
    },
    {
      title: "Feedback Board",
      image: web4,
      github: "https://github.com/gauravsewani/feedback-board",
      demo: "https://feedback-board2.vercel.app/",
      description:
        "A feedback board with a plethora of features allowing users to leave and manage feedback.",
      detailedDescription:
        "Feedback Board is a comprehensive platform that allows users to leave feedback, comments, and suggestions, facilitating better communication and improvement.",
      technologies: [
        "Next.js",
        "MongoDB",
        "Mongoose",
        "AWS",
        "Stripe",
        "TailwindCSS",
      ],
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">Gaurav Sewani</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode((prev) => !prev)}
                  className="cursor-pointer text-2xlr"
                />
              </li>
              <li>
                <Link
                  href="/resume.pdf"
                  download={true}
                  className="bg-gradient-to-tr from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className="lg:flex font-semibold">
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96">
              <Image src={profile} alt="" fill style={{ objectFit: "cover" }} />
            </div>
            <div className="text-center p-10">
              <h2
                className="text-5xl py-2 text-teal-400 font-bold md:text-6xl"
                id="products"
              >
                Gaurav Sewani
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-200">
                Frontend Developer
              </h3>
              <p className="text-lg py-5 leading-8 dark:text-gray-200 text-gray-800 md:text-xl max-w-lg mx-auto">
                I’m a Frontend developer specializing in building (and
                occasionally designing) exceptional digital experiences. I’m
                focused on building responsive websites.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-12 text-gray-600 dark:text-gray-400">
                <a href="https://github.com/gauravsewani/">
                  <AiFillGithub />
                </a>
                <a href="https://www.linkedin.com/in/gauravsewani/">
                  <AiFillLinkedin />
                </a>
                <a href="mailto:lavishgps@gmail.com">
                  <AiFillMail />
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className="">
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center font-bold mt-4">
              Stuff I Know
            </h3>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl  my-10 flex-1 bg-teal-100 dark:bg-gray-800 dark:text-white ">
              <Image
                src={design}
                alt=""
                width={100}
                height={100}
                className="m-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Frontend Development
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">
                Languages I Am Familiar With
              </h4>
              <p className=" py-1">JavaScript</p>
              <p className=" py-1">CSS</p>
              <p className=" py-1">React</p>
              <p className=" py-1">Next Js</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl   my-10 flex-1 bg-teal-100 dark:bg-gray-800 dark:text-white">
              <Image
                src={code}
                width={100}
                height={100}
                alt=""
                className="m-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Backend Development
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let’s make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Know</h4>
              <p className=" py-1">Redux</p>
              <p className=" py-1">Firebase</p>
              <p className=" py-1">MongoDb</p>
              <p className=" py-1">Strapi</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600 font-burtons text-center ">
              ⚒️ My Coding Projects ⚒️
            </h3>
            <p className="text-md py-2 leading-8 text-center text-gray-800 dark:text-gray-200">
              I’ve built cool apps and websites using React and Next Js. Here
              are some of my favorite projects over the course of my journey.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-[2.5rem] py-10 lg:grid-cols-3">
            {projects.map((project, index) => (
              <article
                key={index}
                className="bg-teal-100 dark:bg-gray-800 p-[1.2rem] rounded-3xl hover:bg-teal-100 border border-teal-500 dark:hover:bg-teal-900 hover:bg-gradient-to-t from-transparent to-transparent transition-all ease hover:border-teal-200 hover:dark:border-cyan-500 flex flex-col items-center cursor-pointer"
              >
                <div className="">
                  <img
                    src={project.image.src}
                    className="rounded-3xl h-60 aspect-square md:h-auto md:w-full object-cover"
                    onClick={() => setSelectedProject(project)}
                  />
                </div>
                <h3 className="text-base font-bold py-2 leading-8 text-left text-gray-800 dark:text-gray-200">
                  {project.title}
                </h3>
                <div className="flex gap-4 mb-4 justify-items-start">
                  <a
                    href={project.github}
                    className="w-max inline-block text-gray-800 text-base font-bold px-6 py-2 border border-teal-500 bg-white rounded-md cursor-pointer"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Github
                  </a>
                  <a
                    href={project.demo}
                    className="w-max inline-block text-gray-800 px-6 py-2 border text-base font-bold border-gray-500 rounded-md bg-teal-300 cursor-pointer"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Demo
                  </a>
                </div>
              </article>
            ))}
          </div>
        </section>
      </main>

      {selectedProject && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center overflow-y-auto"
          onClick={(e) => {
            if (e.target.className.includes("bg-opacity-50")) {
              setSelectedProject(null);
            }
          }}
        >
          <div className="relative w-full h-full md:w-2/3 md:h-3/4 bg-white p-8 rounded-lg flex flex-col space-y-8 z-10 dark:bg-black dark:text-white overflow-y-auto">
            <div className="absolute right-4 top-4 md:hidden">
              <button
                onClick={() => setSelectedProject(null)}
                className="text-red-500 text-2xl"
              >
                &times;
              </button>
            </div>
            <div className="flex flex-col md:flex-row space-y-8 md:space-y-0 md:space-x-8">
              <div className="flex justify-center items-center md:h-full md:w-1/2">
                <img
                  src={selectedProject.image.src}
                  className="rounded-3xl h-60 md:h-auto md:w-full object-cover"
                />
              </div>
              <div className="flex flex-col space-y-4 md:w-1/2">
                <h3 className="text-2xl font-bold mb-4">
                  {selectedProject.title}
                </h3>
                <p className="mb-4">{selectedProject.description}</p>
                <p className="mb-4">{selectedProject.detailedDescription}</p>
                <div className="flex flex-col space-y-2">
                  <h4 className="text-lg font-bold">Technologies Used:</h4>
                  <div className="flex flex-wrap gap-2">
                    {selectedProject.technologies.map((tech, index) => (
                      <span
                        key={index}
                        className="bg-gray-200 rounded-full font-bold dark:text-black px-3 py-1 text-sm"
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex gap-4">
                  <button
                    onClick={() =>
                      window.open(selectedProject.github, "_blank")
                    }
                    className="w-max inline-block text-gray-800 text-base font-bold px-6 py-2 border border-teal-500 bg-white rounded-md cursor-pointer"
                  >
                    Github
                  </button>
                  <button
                    onClick={() => window.open(selectedProject.demo, "_blank")}
                    className="w-max inline-block text-gray-800 px-6 py-2 border text-base font-bold border-gray-500 rounded-md bg-teal-300 cursor-pointer"
                  >
                    Demo
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
